# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Vox
  - !type:OverallPlaytimeRequirement
    time: 5h # Vanilla-RoleTime
  - !type:AgeRequirement
    requiredAge: 32 # Vanilla
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
