- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 360000 #100 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 28
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: Skill
      RangeWeaponLevel: 2
      MeleeWeaponLevel: 2
      MedicineLevel: 1
      ChemistryLevel: 2
      EngineeringLevel: 1
      BuildingLevel: 0
      ResearchLevel: 0
      Atmosphere: true
      Piloting: true
      MusInstruments: true
      Botany: false
      Bureaucracy: true
    - type: AddSkillPoints
      Points: 1

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    # gloves: ClothingHandsGlovesCaptain #vanilla-loadouts
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
