- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 #5 hrs # Vanilla-RoleTime
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 18000 #5 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 28
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Speech
        speechSounds: Soldier
        soundCooldownTime: 0.1
      - type: TriggerOnMobstateChange
        mobState:
        - Critical
      - type: EmitSoundOnTrigger
        sound:
          collection: SoldierDeath
          params:
            volume: -4
      - type: Skill
        PilotingLevel: 2
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 3
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
