- type: randomHumanoidSettings
  id: VisitorSeniorCooker
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorWalter
      roleLoadout: [ RoleSurvivalExtended ]

- type: randomHumanoidSettings
  id: VisitorJuniorCooker
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorJessy
      roleLoadout: [ RoleSurvivalExtended ]