- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 22
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skill
      PilotingLevel: 1
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 0
      MedicineLevel: 0
      ChemistryLevel: 1
      EngineeringLevel: 3
      BuildingLevel: 3
      ResearchLevel: 0
      InstrumentationLevel: 2

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
