- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 0
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 3
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  #storage:
    #back:
    #- Stuff
