- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 2
        MedicineLevel: 2
        ChemistryLevel: 2
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        Atmosphere: false
        Piloting: false
        MusInstruments: true
        Botany: false
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1

- type: startingGear
  id: PsychologistGear
  equipment:
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist
