- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 2
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 3
        MedicineLevel: 0
        ChemistryLevel: 1
        EngineeringLevel: 1
        BuildigLevel: 1
        ResearchLevel: 1
        RoboticsLevel: 1

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
