- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 #10 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 23
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 2
        MeleeWeaponLevel: 2
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 2
        ResearchLevel: 0
        InstrumentationLevel: 2
        Piloting: true
        MusInstruments: true
        Botany: false
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1
        
- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
