- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs Vanilla-roletime
    - !type:AgeRequirement
      requiredAge: 22
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 3
        RangeWeaponLevel: 2
        MeleeWeaponLevel: 3
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 1
        BuildigLevel: 1
        ResearchLevel: 0
        RoboticsLevel: 0

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
