- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 3
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 1
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 1
        BuildingLevel: 1
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: PilotGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckTieRed
    pocket1: WeaponPistolMk58
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistol
