using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Rayten.TapePlayer;

//<Label Name="SongName" Text="-" MaxWidth="300" RectClipContent="True"/>
//<Label Name="InsertedTape" Text="{Loc 'tapeplayer-menu-tape'}" />

[GenerateTypedNameReferences]
public sealed partial class TapePlayerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;
    private bool _playState;
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<float>? SetCD;
    public event Action<float>? SetVolume;
    private EntityUid? _audio;
    private float _Timerlock;
    public TapePlayerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();
        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };
        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };
        PlaySlider.OnReleased += PlaySliderKeyUp;
        VolumeSlider.OnReleased += VolumeSliderKeyUp;

        SetButtonPlayPause(_audioSystem.IsPlaying(_audio), force: true);
    }
    public TapePlayerMenu(AudioSystem audioSystem)
    {
        _audioSystem = audioSystem;
    }
    public void SetAudio(EntityUid? audio)
    {
        _audio = audio;
    }
    public void SetVolumeSlider(float volume)
    {
        VolumeSlider.Value = volume;
    }
    private void PlaySliderKeyUp(Slider args)
    {
        SetCD?.Invoke(PlaySlider.Value);
        _Timerlock = 0.1f;
    }
    private void VolumeSliderKeyUp(Slider args)
    {
        SetVolume?.Invoke(VolumeSlider.Value / 100f);
        _Timerlock = 0.1f;
    }
    public void SetButtonPlayPause(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;
        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }
        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }
            public void SetSelectedSong(float length)
        {
            PlaySlider.MaxValue = length;
            PlaySlider.SetValueWithoutEvent(0.1f);
        }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_Timerlock > 0f)
        { _Timerlock -= args.DeltaSeconds; }
        PlaySlider.Disabled = _Timerlock > 0f;
        VolumeSlider.Disabled = _Timerlock > 0f;
        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} - {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $"00:00 - 00:00";
        }
        if (PlaySlider.Grabbed)
            return;
        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaySlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaySlider.SetValueWithoutEvent(0.1f);
        }
        SetButtonPlayPause(_audioSystem.IsPlaying(_audio, audio));
    }
}
