- type: job
  id: Passenger
  name: job-name-passenger
  setPreference: false # Rayten-graytidegate
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 1
        MeleeWeaponLevel: 1
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        Atmosphere: false
        Piloting: false
        MusInstruments: true
        Botany: false
        Bureaucracy: false
      - type: AddSkillPoints
        Points: 1
#  access: # Corvax-MRP
#  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
