- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: Skill
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 1
      MedicineLevel: 2
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      Atmosphere: false
      Piloting: false
      MusInstruments: true
      Botany: false
      Bureaucracy: true
    - type: AddSkillPoints
      Points: 1

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
