- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: Skill
      PilotingLevel: 0
      RangeWeaponLevel: 1
      MeleeWeaponLevel: 0
      MedicineLevel: 0
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      InstrumentationLevel: 0

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
