- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skill
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 0
      MedicineLevel: 0
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 3
      InstrumentationLevel: 0
      Piloting: false
      MusInstruments: true
      Botany: false
      Bureaucracy: true
    - type: AddSkillPoints
      Points: 1

- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d20Dice
    pocket2: HandLabeler # for making named bestsellers
  storage:
    back:
    - BookRandom
