- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 90000 #25 hrs # Vanilla-RoleTime
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
      preventWriting: true
    - type: FrenchAccent
    - type: Skill
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 1
      MedicineLevel: 1
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 1
      ResearchLevel: 0
      Atmosphere: false
      Piloting: false
      MusInstruments: true
      Botany: false
      Bureaucracy: true
    - type: AddSkillPoints
      Points: 1

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: MimePDA
    pocket1: CrayonMime
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
    event: !type:InvisibleWallActionEvent
