- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hop # Corvax-JobSupervisors
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer
  - !type:AddComponentSpecial
    components:
    - type: Skill
      PilotingLevel: 0
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 0
      MedicineLevel: 0
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      InstrumentationLevel: 0
    - type: AddSkillPoints
      Points: 6

- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
