- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skill
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 0
      MedicineLevel: 0
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      Atmosphere: false
      Piloting: false
      MusInstruments: true
      Botany: true
      Bureaucracy: false
    - type: AddSkillPoints
      Points: 3

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
