- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 54000 #15 hrs # Vanilla-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skill
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 3
        BuildingLevel: 2
        ResearchLevel: 3
        Atmosphere: true
        Piloting: false
        MusInstruments: true
        Botany: false
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1


- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
