- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10800 #3 hrs # Vanilla-RoleTime
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 0
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 2
        ChemistryLevel: 1
        EngineeringLevel: 0
        BuildingLevel: 1
        ResearchLevel: 3
        InstrumentationLevel: 3

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff
